# Generated by Django 4.0.10 on 2024-05-01 10:47

from django.db import migrations, models
import menu.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
                ('time_minutes', models.IntegerField(verbose_name='Preparation time in min')),
                ('vegetarian', models.BooleanField(verbose_name='Is vegetarian')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Modified')),
                ('image', models.ImageField(blank=True, null=True, upload_to=menu.models.dish_image_file_path)),
            ],
            options={
                'verbose_name': 'Dish',
                'verbose_name_plural': 'Dishes',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Menu name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Modified')),
                ('dishes', models.ManyToManyField(to='menu.dish', verbose_name='Dish')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
            },
        ),
    ]
