# Generated by Django 4.0.10 on 2023-02-23 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_dish_options_alter_menu_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dish',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='menu',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
