# Generated by Django 4.0.10 on 2023-02-23 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dish_created_date_dish_modified_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dish',
            name='modified_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='menu',
            name='modified_date',
            field=models.DateField(auto_now=True),
        ),
    ]
