# Generated by Django 4.0.10 on 2023-02-24 11:09

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_dish_created_date_alter_dish_modified_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.dish_image_file_path),
        ),
        migrations.AlterField(
            model_name='dish',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Menu name'),
        ),
    ]
